### ISSUE TITLE
Viewing on energy dashboard

### ISSUE THREAD

**Issue by stefanolson** [cabberley/HA_RedbackTech#12]
So thrilled to finally have a way to access the inverter and battery from home assistant. I was very excited to see how it would integrate with the energy dashboard. but I feel like I'm missing something obvious and can't make it work.  Everything appears to have been created correctly, for example I have:
PV Power Instantaneous
Grid Phase A Active Exported Power Instantaneous
Grid Phase A Active Imported Power Instantaneous
Battery Stack Power Negative Is Charging

All of which seem to be the correct values based on what I can see in the app.  however, when I go to the energy dashboard and try and  use any of those values there none of them are available in the  dropdowns in the energy dashboard configuration section.  And the battery seems to require two values, one  and one out which doesn't seem to be what we have in the list above.

Is there a trick to getting this going?

Thanks!

**Comment by stefanolson** [comment]
Ok, looks like HA needs these ones:
Grid Import All Time Energy
Grid Export All Time Energy
PV All Time Energy
Battery Stack Discharge All Time Energy
Battery Stack Charge All Time Energy

So the numbers appear slightly differently in home assistant to how they appear in the app.  So far seems to add up.  If I've got this right you can probably close this.

**Comment by cabberley** [comment]
@stefanolson yes HA energy dashboard uses energy values not power values. 
Not sure if know the difference, think of driving a car, power is the speed your doing, energy is the distance you travelled in the last x period.

Thanks for trying out the integration!
