### ISSUE TITLE
Failed Setup, will retry

### ISSUE THREAD

**Issue by LachyGoshi** [cabberley/HA_RedbackTech#2]
![Screenshot_20240607-200334](https://github.com/cabberley/HA_RedbackTech/assets/60020083/03243808-7585-452f-a93e-889a28cac83e)
![Screenshot_20240607-201612](https://github.com/cabberley/HA_RedbackTech/assets/60020083/f01b4fc3-0ab9-4155-9b84-de73d9fba45b)
![Screenshot_20240607-200347](https://github.com/cabberley/HA_RedbackTech/assets/60020083/54719766-7c8f-4fd7-a09c-42a028cbb1cb)
Hi mate, great stuff but she no go bang for me ☹️

Any logs I can help look in to? I've tried a few times by deleting the failed entry and re setting up, and I'm sure my API and portal logins are correct.

![Screenshot_20240607-200146](https://github.com/cabberley/HA_RedbackTech/assets/60020083/79b6e67e-170c-41e1-bae8-292f2aafaade)
I even tried renaming it when logging in incase there was a conflict with one of the previous integrations.

Do I need to delete them at all first? I didn't think so.

**Comment by cabberley** [comment]
You will only be able to have 1 entry for each client_id account which should have the Inverters and batterys that that API can see.
![image](https://github.com/cabberley/HA_RedbackTech/assets/26394346/c372c075-dd0f-4fe2-8f99-2c0937084810)

I have tried to reproduce it, but can't. I have seen when I was working on this that if the Python module didn't download in time when it updates, I did get a config error.  
Can you try:
1. Deleting all the configs, 
2. Restarting HA and trying to add it again? 
3. If it does error during setup can you have a look at the logs on HA. 
4. Download the Full Logs.  
5. Finally Restart HA again and see if after the restart it loads correctly?

**Comment by LachyGoshi** [comment]
![Screenshot_20240616-192547](https://github.com/cabberley/HA_RedbackTech/assets/60020083/103ef08f-94cc-4b92-98d1-959c395a2d92)
Where is the best place to find logs specific to the integration? Is there an easy way to filter the system logs just to find related entries?

I have just fully removed and reinstalled the latest version, same error still shows as above but I did notice that tapping on it brings up the message about my SI (non battery inverter) not having mode set options. This is true, it is pretty much a dumb inverter that has no modes.

So looks like at least the integration is logging in to the API/portal ok, but needs some filter to determine if it is hybrid/battery controller or not.

**Comment by cabberley** [comment]
@LachyGoshi the details I need should be in your HA system logs. (Settings\System\Logs).
In the list of logs there should be one referencing the redback integration. and if you open it up it should have a lot of lines with file names and line numbers similar to this from a different integration. It is those details I need to start with. It may help if you try and reload the integration, it should generate a new error in the logs and be at the top, making it easier to find.

![image](https://github.com/cabberley/HA_RedbackTech/assets/26394346/a628f700-b9a1-401d-81d1-5e123713ac99)

**Comment by LachyGoshi** [comment]
Yeah that's where I have been looking, nothing in there from "redback technologies". If I re enable Juices integration I sometimes get the below message in the logs:

This error originated from a custom integration.

Logger: custom_components.redback
Source: helpers/update_coordinator.py:325
integration: Redback Technologies Portal (documentation, issues)
First occurred: 17:55:20 (2 occurrences)
Last logged: 19:57:21

Error requesting redback data: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.redbacktech.com/Api/v2/Auth/token')

But with juices integration disabled, home assistant restarted, no entries from this integration. 

Is there a logging level I can increase to? I do have "debug logging" enabled on this integration.

![Screenshot_20240617-201021](https://github.com/cabberley/HA_RedbackTech/assets/60020083/89a184c1-674e-4233-b66b-dc82e1ab9f31)

**Comment by cabberley** [comment]
@LachyGoshi I have made some code modifications, I suspect the HTTP 500 error is due to this inverter not having "schedules" that the battery\hybrid inverters have. This one has relays. Do you use the smart relays on this inverter? They are handled through a different API. In HACS Could you please update the "Redback Technologies SmartHybrid" Integration, Then redownload, but you will need to enable Beta on the redownload screen like the image here and install 2024.6.4b1 and let me know how that goes.
ALSO IMPORANTLY, until you can try this beta could you disable the integration in settings/Devices and Services, I have a suspicion that your error is causing a problem on Redbacks APIs and causing HTTP 500 errors sporadically for others if they hot the API at the same time as your integration tries to reload.

![image](https://github.com/cabberley/HA_RedbackTech/assets/26394346/111911de-4fe6-490b-a2db-52f3bf7fc3d5)

**Comment by LachyGoshi** [comment]
![Screenshot_20240618-194237](https://github.com/cabberley/HA_RedbackTech/assets/60020083/07c1d099-8f9b-45b0-9576-be3bf360e6e0)
![Screenshot_20240618-194303](https://github.com/cabberley/HA_RedbackTech/assets/60020083/6fcf90ef-b4f2-46e1-b10b-598060b9580b)
![Screenshot_20240618-194345](https://github.com/cabberley/HA_RedbackTech/assets/60020083/62fb71b6-8cb4-4e90-b9f1-acc97ae689b3)
![Screenshot_20240618-194514](https://github.com/cabberley/HA_RedbackTech/assets/60020083/bb199930-0505-464c-a37b-7c0a0a67ddcf)
![Screenshot_20240618-194548](https://github.com/cabberley/HA_RedbackTech/assets/60020083/94fad1bd-cd7a-4531-a125-1ca99cb34f1c)
![Screenshot_20240618-194804](https://github.com/cabberley/HA_RedbackTech/assets/60020083/3f1c2d35-39a9-48ae-afba-8a87c00485fd)
![Screenshot_20240618-194807](https://github.com/cabberley/HA_RedbackTech/assets/60020083/93a006ae-014f-4eb6-b6b4-f0b132167b3a)
![Screenshot_20240618-194754](https://github.com/cabberley/HA_RedbackTech/assets/60020083/d8275edb-d806-4230-99ef-688c47ab43bb)
![Screenshot_20240618-195323](https://github.com/cabberley/HA_RedbackTech/assets/60020083/44cbba8b-27fe-4508-a178-649ca441e174)
Amazing, seems to be loading now!

I successfully added a quick schedule and it's shown in the web portal and started!

What is the difference between active event inverter mode and scheduled inverter mode.... Wondering why the scheduled would be charge when it is actively running my discharge schedule?
![Screenshot_20240618-195146](https://github.com/cabberley/HA_RedbackTech/assets/60020083/ff108bb5-4d42-4475-b491-ea554bede676)

![Screenshot_20240618-195238](https://github.com/cabberley/HA_RedbackTech/assets/60020083/9b57b84c-f96a-408b-bf63-aef58283df1f)

**Comment by cabberley** [comment]
@LachyGoshi Thats great news! Good to see you can see all of your Redback devices now!
1. I just write this in the wiki [active vs Scheduled events](https://github.com/cabberley/HA_RedbackTech/wiki/Active-vs-Scheduled-Events) .  Let me know if that makes sense? 
2. Do you have anything connected to the Relays on your SI5000? and if so do you use the 'smart' controls of it? There is a separate API that enables you to control what they do, similar to the schedule of the SH5000.  have some more work to do on the code and just prioritising my list. 
3. In the next release I will put some more logic in the code to remove the buttons from the SI5000 device as they aren't relevant for that model.

**Comment by cabberley** [comment]
@LachyGoshi I have just release version 2024.6.6 which should be better for you. In particular it should no longer add the buttons to the SI Inverter, as they are irrelevant. If you provide some more info to the Q's above I can add that into a future release as well.

**Comment by cabberley** [comment]
That's all good, nice to hear the work I have done has helped!

Still have some more stuff I want to expose and surface from redback. 
I also have some other info from them which I will add onto the readme, so help with curtailment and other things.

**Comment by LachyGoshi** [comment]
![Screenshot_20240620-192110](https://github.com/cabberley/HA_RedbackTech/assets/60020083/287ba56d-3d69-427c-9c29-1d9468da3bcf)
![Screenshot_20240620-192150](https://github.com/cabberley/HA_RedbackTech/assets/60020083/aa40b196-996f-4977-8612-0e1b61a4abfa)
![Screenshot_20240620-192159](https://github.com/cabberley/HA_RedbackTech/assets/60020083/6d241662-e0ce-472c-bc7e-93dfdccf0cde)
![Screenshot_20240620-192206](https://github.com/cabberley/HA_RedbackTech/assets/60020083/02257f36-2110-4261-8571-be151fa32830)
![Screenshot_20240620-192257](https://github.com/cabberley/HA_RedbackTech/assets/60020083/70dbbdbe-7a65-4f61-b009-908605b822a2)
After deleting the old config, I just downloaded the latest 6.6 release and re set it up.

SI page much more cleaned up (thanks). There are still some sensors listed for my single phase SI5000 that I don't think are relevant (all the phase B and C) and a battery count still listed in diagnostic section.

Overall, this is great, thanks so much. I will have to experiment with the call service action for the immediate setting of hybrid inverter mode/power as that's what I still use "inverter mode set" integration for.

**Comment by LachyGoshi** [comment]
This has been working well last couple of days so I'll close it shortly. 

But before I do, just wondering:
Is there a clear definition for all the values listed in the inverter modes? As in what Ppv, xmax, Pinv Pbatt. I can take a guess at what I'm pretty sure these are but it would be nice to know I'm thinking straight.

How can I do the service call for a quick mode change, this is what I still use your old integration for but if you share some examples of how to use the service call I will be able to remove the old integration and just use this one!

**Comment by LachyGoshi** [comment]
New version working ok with my two inverters. One hybrid with battery, other normal grid tied inverter. Setup as being on same site.
